### ISSUE TITLE
connection problem with postgres 16...

### ISSUE THREAD

**Issue by JYPochez** [ethanak/SimplePgSQL#10]
Hi there...
don't know if this is still listened, but I cannot connect with a postgres 16 server...
the arduino (here en esp8266 module) always tell "Unsupported auth method"
I changed the authentification method from scram to md5 in pg_hba.conf
and set the method to md5 in postgresql.conf
and retyped the user password
but still unable to authenticate...

any idea ?
thanks.

**Comment by ethanak** [comment]
As I have no 8266 module now and no access do version 16 of PostgreSQL server - I cannot check it. I'll try next week.

**Comment by JYPochez** [comment]
is it possible to add the scram auth method to an esp8266 ? or is too much processing power for it ?

**Comment by JYPochez** [comment]
just downgraded the pg server to v12 and now the SimplePgSql example sketch works fine.

**Comment by ethanak** [comment]
Problem is probably in PostgreSQL 16: even if configured to md5 requires SASL auth.
In local network you can use password auth.
At now implementation of SASL is not provided for ESP8266.
